# Generated by Django 5.0.6 on 2024-06-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SharedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_1', models.EmailField(max_length=254)),
                ('name_1', models.CharField(max_length=100)),
                ('email_2', models.EmailField(max_length=254)),
                ('article_info', models.JSONField()),
            ],
            options={
                'unique_together': {('email_1', 'email_2', 'article_info')},
            },
        ),
    ]
